remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: VBD Privacy Policy
description: Privacy Policy for VBD - Volunteers of Bangladesh Android App
show_downloads: false

github:
  is_project_page: false
